on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: myacs92.azurecr.io
        username: ${{ secrets.acr_myacs92_username }}
        password: ${{ secrets.acr_myacs92_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t myacs92.azurecr.io/akssourav:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push myacs92.azurecr.io/akssourav:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_akssourav_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-sourava648 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-sourava648`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-sourava648
        container-registry-url: myacs92.azurecr.io
        container-registry-username: ${{ secrets.acr_myacs92_username }}
        container-registry-password: ${{ secrets.acr_myacs92_password }}
        secret-name: akssouravdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-sourava648
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          myacs92.azurecr.io/akssourav:${{ github.sha }}
        imagepullsecrets: |
          akssouravdockerauth
